name: CI/CD Java with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      
      - name: Bump version
        run: |
          mvn org.codehaus.mojo:build-helper-maven-plugin:3.5.0:parse-version \
              org.codehaus.mojo:versions-maven-plugin:2.16.2:set \
              -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} \
              org.codehaus.mojo:versions-maven-plugin:2.16.2:commit

    
      - name: Build JAR
        run: mvn clean package -DskipTests

     
      - name: Extract project version
        run: echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:${{ env.PROJECT_VERSION }} .

     
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:${{ env.PROJECT_VERSION }}

    
     
